export const destination = {
  name: 'destination',
  title: 'Destinations',
  type: 'document',
  groups: [
    { name: 'essentials', title: 'Essentials', default: true },
    { name: 'content', title: 'Content' },
    { name: 'planning', title: 'Planning & Trip Ideas' },
    { name: 'seo', title: 'SEO' },
  ],
  fields: [
    {
      name: 'name',
      title: 'Name',
      type: 'string',
      validation: (Rule: any) => Rule.required(),
      description: 'e.g. Mauritius, Western Cape, Cape Town',
      group: 'essentials',
    },
    {
      name: 'slug',
      title: 'URL Slug',
      type: 'slug',
      options: { source: 'name' },
      validation: (Rule: any) => Rule.required(),
      group: 'essentials',
    },
    {
      name: 'level',
      title: 'Level',
      type: 'string',
      options: {
        list: [
          { title: 'Region', value: 'region' },
          { title: 'Country', value: 'country' },
          { title: 'Province / State / Area', value: 'province' },
          { title: 'City / Town', value: 'city' },
        ],
      },
      validation: (Rule: any) => Rule.required(),
      description: 'What level in the hierarchy is this destination?',
      group: 'essentials',
    },
    {
      name: 'region',
      title: 'Region',
      type: 'string',
      options: {
        list: [
          { title: 'Indian Ocean Islands', value: 'indian-ocean-islands' },
          { title: 'Southern Africa', value: 'southern-africa' },
          { title: 'East Africa', value: 'east-africa' },
          { title: 'Europe', value: 'europe' },
          { title: 'Asia', value: 'asia' },
          { title: 'Americas', value: 'americas' },
          { title: 'Polar & Expedition', value: 'polar-expedition' },
          { title: 'Ocean Voyages', value: 'ocean-voyages' },
        ],
      },
      validation: (Rule: any) => Rule.required(),
      description: 'Which broad region does this destination belong to?',
      group: 'essentials',
    },
    {
      name: 'parent',
      title: 'Parent Destination',
      type: 'reference',
      to: [{ type: 'destination' }],
      description: 'e.g. Western Cape\'s parent is South Africa. Cape Town\'s parent is Western Cape.',
      group: 'essentials',
    },
    {
      name: 'heroImage',
      title: 'Hero Image',
      type: 'image',
      options: { hotspot: true },
      fields: [
        {
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
          description: 'Describe the image for SEO',
          validation: (Rule: any) => Rule.required().warning('Alt text is important for SEO'),
        },
      ],
      group: 'essentials',
    },
    {
      name: 'published',
      title: 'Published',
      type: 'boolean',
      initialValue: false,
      description: 'Toggle to make this destination visible on the website',
      group: 'essentials',
    },
    {
      name: 'description',
      title: 'Description',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'A beautifully written introduction that captures the imagination — naturally incorporate primary SEO keywords. Shown at the top of the destination page.',
      group: 'content',
    },
    {
      name: 'whyYoullLoveIt',
      title: "Why You'll Love It",
      type: 'text',
      rows: 3,
      description: 'A short line that emotionally connects with the reader, e.g. "If your idea of luxury is complete privacy, exceptional service and waking to endless shades of turquoise, the Maldives offers one of the world\'s most exclusive island escapes."',
      group: 'content',
    },
    {
      name: 'highlights',
      title: 'Highlights',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Key highlights for this destination',
      group: 'content',
    },
    {
      name: 'signatureLuxuryExperiences',
      title: 'Signature Luxury Experiences',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'Standout bespoke experiences unique to this destination, e.g. Sunset champagne cruises, Private sandbank dining, Swimming with whale sharks',
      group: 'content',
    },
    {
      name: 'travelTips',
      title: 'Travel Tips',
      type: 'array',
      of: [{ type: 'block' }],
      description: 'Insider advice rather than generic recommendations, e.g. which areas suit honeymooners, when to book, how to combine destinations',
      group: 'content',
    },
    {
      name: 'practicalInformation',
      title: 'Practical Information',
      type: 'object',
      description: 'Clean, consistent practical details shown in a reference panel on the destination page',
      fields: [
        { name: 'currency', title: 'Currency', type: 'string' },
        { name: 'language', title: 'Language', type: 'string' },
        { name: 'flightTime', title: 'Flight Time', type: 'string' },
        { name: 'timeZone', title: 'Time Zone', type: 'string' },
        { name: 'visaRequirements', title: 'Visa Requirements', type: 'string' },
        { name: 'gettingAround', title: 'Getting Around', type: 'string' },
        { name: 'health', title: 'Health', type: 'string' },
        { name: 'electricity', title: 'Electricity', type: 'string' },
        { name: 'tipping', title: 'Tipping', type: 'string' },
        { name: 'idealStay', title: 'Ideal Stay', type: 'string' },
      ],
      group: 'content',
    },
    {
      name: 'bestTimeToVisit',
      title: 'Best Time to Visit (Short Summary)',
      type: 'string',
      description: 'e.g. May to October for dry season — shown in the hero and sidebar summary',
      group: 'planning',
    },
    {
      name: 'bestTimeToVisitDetail',
      title: 'Best Time to Visit — Seasonal Breakdown',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'season',
          title: 'Season / Activity',
          fields: [
            {
              name: 'period',
              title: 'Period',
              type: 'string',
              description: 'e.g. "Beach holidays: May–December" or "Honeymoon: September–November"',
              validation: (Rule: any) => Rule.required(),
            },
            {
              name: 'description',
              title: 'Why this period',
              type: 'text',
              rows: 2,
            },
          ],
          preview: {
            select: { title: 'period', subtitle: 'description' },
          },
        },
      ],
      description: 'Optional detailed, season-by-season breakdown shown in the page body, explaining why each period is ideal',
      group: 'planning',
    },
    {
      name: 'perfectFor',
      title: 'Perfect For',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'Traveller types this destination suits, e.g. Honeymoons, Families, Wellness Retreats, Adventure, Diving',
      group: 'planning',
    },
    {
      name: 'combineWith',
      title: 'Combine With',
      type: 'array',
      of: [{ type: 'string' }],
      options: { layout: 'tags' },
      description: 'Destinations or trip themes that pair well with this one, e.g. Sri Lanka, Dubai, South African Safari',
      group: 'planning',
    },
    {
      name: 'seoTitle',
      title: 'SEO Title',
      type: 'string',
      description: 'Ideally 50–60 characters.',
      validation: (Rule: any) => Rule.max(60).warning('SEO titles over 60 characters may be truncated in Google'),
      group: 'seo',
    },
    {
      name: 'seoDescription',
      title: 'SEO Description',
      type: 'text',
      rows: 3,
      description: 'Ideally 140–160 characters.',
      validation: (Rule: any) => Rule.max(160).warning('SEO descriptions over 160 characters may be truncated in Google'),
      group: 'seo',
    },
  ],
  preview: {
    select: {
      title: 'name',
      level: 'level',
      region: 'region',
      media: 'heroImage',
      parent: 'parent.name',
    },
    prepare({ title, level, region, media, parent }: any) {
      const subtitle = parent ? `${parent} → ${title}` : `${region} · ${level}`
      return { title, subtitle, media }
    },
  },
}